name: Build Mycelis Firmware

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install and Build ESP-IDF
        run: |
          git clone -b v5.3 --recursive https://github.com/espressif/esp-idf.git $HOME/esp/esp-idf
          cd $HOME/esp/esp-idf
          ./install.sh esp32s3
          . ./export.sh
          cd $GITHUB_WORKSPACE
          python scripts/build.py spotpear/sp-esp32-s3-1.28-box --name sp-esp32-s3-1.28-box

      - name: Save firmware
        uses: actions/upload-artifact@v4
        with:
          name: Mycelis-firmware
          path: |
            build/*.bin


