name: Build Mycelis Firmware

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          version: v5.3

      - name: Configure and Build Board
        run: |
          . $IDF_PATH/export.sh
          python scripts/build.py spotpear/sp-esp32-s3-1.28-box --name sp-esp32-s3-1.28-box

      - name: Save firmware
        uses: actions/upload-artifact@v4
        with:
          name: Mycelis-firmware
          path: |
            build/*.bin
